name: Run lints & test

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]
  schedule:
    - cron: '19 2 * * 4'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ln -s .. _work
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/AMD64Lib"
          path: "_work/AMD64Lib"
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/ACPILib"
          path: "_work/ACPILib"
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/SulfurDioxide"
          path: "_work/SulfurDioxide"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ln -s .. _work
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/AMD64Lib"
          path: "_work/AMD64Lib"
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/ACPILib"
          path: "_work/ACPILib"
      - uses: actions/checkout@v2
        with:
          repository: "BoxOperatingSystem/SulfurDioxide"
          path: "_work/SulfurDioxide"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
