name: Run lints & test

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ln -s .. _work
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/AMD64"
          path: "_work/AMD64"
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/ACPI"
          path: "_work/ACPI"
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/Kaboom"
          path: "_work/Kaboom"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ln -s .. _work
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/AMD64"
          path: "_work/AMD64"
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/ACPI"
          path: "_work/ACPI"
      - uses: actions/checkout@v2
        with:
          repository: "Firework-OS/Kaboom"
          path: "_work/Kaboom"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
